// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
public import Foundation
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/get(getButtonDestinations)`.
    func getButtonDestinations(_ input: Operations.GetButtonDestinations.Input) async throws -> Operations.GetButtonDestinations.Output
    /// - Remark: HTTP `POST /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/post(registerButtonDestination)`.
    func registerButtonDestination(_ input: Operations.RegisterButtonDestination.Input) async throws -> Operations.RegisterButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/heartbeat/post(heartbeatButtonDestination)`.
    func heartbeatButtonDestination(_ input: Operations.HeartbeatButtonDestination.Input) async throws -> Operations.HeartbeatButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/select`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/select/post(selectButtonDestination)`.
    func selectButtonDestination(_ input: Operations.SelectButtonDestination.Input) async throws -> Operations.SelectButtonDestination.Output
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/complete/post(completeButtonTake)`.
    func completeButtonTake(_ input: Operations.CompleteButtonTake.Input) async throws -> Operations.CompleteButtonTake.Output
    /// - Remark: HTTP `DELETE /v1/button-destinations/{id}`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/delete(unregisterButtonDestination)`.
    func unregisterButtonDestination(_ input: Operations.UnregisterButtonDestination.Input) async throws -> Operations.UnregisterButtonDestination.Output
    /// - Remark: HTTP `GET /v1/audio-sources`.
    /// - Remark: Generated from `#/paths//v1/audio-sources/get(listAudioSources)`.
    func listAudioSources(_ input: Operations.ListAudioSources.Input) async throws -> Operations.ListAudioSources.Output
    /// - Remark: HTTP `POST /v1/captures`.
    /// - Remark: Generated from `#/paths//v1/captures/post(startCapture)`.
    func startCapture(_ input: Operations.StartCapture.Input) async throws -> Operations.StartCapture.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/capture/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/capture/heartbeat/post(heartbeatCapture)`.
    func heartbeatCapture(_ input: Operations.HeartbeatCapture.Input) async throws -> Operations.HeartbeatCapture.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/capture/stop`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/capture/stop/post(stopCapture)`.
    func stopCapture(_ input: Operations.StopCapture.Input) async throws -> Operations.StopCapture.Output
    /// - Remark: HTTP `GET /v1/health`.
    /// - Remark: Generated from `#/paths//v1/health/get(getHealth)`.
    func getHealth(_ input: Operations.GetHealth.Input) async throws -> Operations.GetHealth.Output
    /// - Remark: HTTP `GET /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/get(getPreferences)`.
    func getPreferences(_ input: Operations.GetPreferences.Input) async throws -> Operations.GetPreferences.Output
    /// - Remark: HTTP `PUT /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/put(updatePreferences)`.
    func updatePreferences(_ input: Operations.UpdatePreferences.Input) async throws -> Operations.UpdatePreferences.Output
    /// - Remark: HTTP `GET /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/get(listGenerations)`.
    func listGenerations(_ input: Operations.ListGenerations.Input) async throws -> Operations.ListGenerations.Output
    /// - Remark: HTTP `POST /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/post(createGeneration)`.
    func createGeneration(_ input: Operations.CreateGeneration.Input) async throws -> Operations.CreateGeneration.Output
    /// - Remark: HTTP `GET /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/get(getGeneration)`.
    func getGeneration(_ input: Operations.GetGeneration.Input) async throws -> Operations.GetGeneration.Output
    /// - Remark: HTTP `DELETE /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delete(deleteGeneration)`.
    func deleteGeneration(_ input: Operations.DeleteGeneration.Input) async throws -> Operations.DeleteGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/audio/{kind}/post(appendAudio)`.
    func appendAudio(_ input: Operations.AppendAudio.Input) async throws -> Operations.AppendAudio.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/finish`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/finish/post(finishGeneration)`.
    func finishGeneration(_ input: Operations.FinishGeneration.Input) async throws -> Operations.FinishGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/cancel`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/cancel/post(cancelGeneration)`.
    func cancelGeneration(_ input: Operations.CancelGeneration.Input) async throws -> Operations.CancelGeneration.Output
    /// - Remark: HTTP `POST /v1/generations/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delivery/post(recordDelivery)`.
    func recordDelivery(_ input: Operations.RecordDelivery.Input) async throws -> Operations.RecordDelivery.Output
    /// A bounded NDJSON stream of complete GenerationRecord values, with the latest record repeated as a two-second heartbeat. Ends after a terminal record.
    ///
    /// - Remark: HTTP `GET /v1/generations/{id}/events`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/events/get(generationEvents)`.
    func generationEvents(_ input: Operations.GenerationEvents.Input) async throws -> Operations.GenerationEvents.Output
    /// - Remark: HTTP `GET /v1/generations/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/artifacts/{filename}/get(downloadArtifact)`.
    func downloadArtifact(_ input: Operations.DownloadArtifact.Input) async throws -> Operations.DownloadArtifact.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/known`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/known/post(knownWisprFlowIDs)`.
    func knownWisprFlowIDs(_ input: Operations.KnownWisprFlowIDs.Input) async throws -> Operations.KnownWisprFlowIDs.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/post(beginWisprFlowImport)`.
    func beginWisprFlowImport(_ input: Operations.BeginWisprFlowImport.Input) async throws -> Operations.BeginWisprFlowImport.Output
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/dictionary`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/dictionary/put(archiveWisprFlowDictionary)`.
    func archiveWisprFlowDictionary(_ input: Operations.ArchiveWisprFlowDictionary.Input) async throws -> Operations.ArchiveWisprFlowDictionary.Output
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/artifacts/{filename}/put(uploadWisprFlowArtifact)`.
    func uploadWisprFlowArtifact(_ input: Operations.UploadWisprFlowArtifact.Input) async throws -> Operations.UploadWisprFlowArtifact.Output
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/complete/post(completeWisprFlowImport)`.
    func completeWisprFlowImport(_ input: Operations.CompleteWisprFlowImport.Input) async throws -> Operations.CompleteWisprFlowImport.Output
    /// - Remark: HTTP `DELETE /v1/imports/wispr-flow/{id}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/delete(cancelWisprFlowImport)`.
    func cancelWisprFlowImport(_ input: Operations.CancelWisprFlowImport.Input) async throws -> Operations.CancelWisprFlowImport.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/get(getButtonDestinations)`.
    public func getButtonDestinations(headers: Operations.GetButtonDestinations.Input.Headers = .init()) async throws -> Operations.GetButtonDestinations.Output {
        try await getButtonDestinations(Operations.GetButtonDestinations.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /v1/button-destinations`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/post(registerButtonDestination)`.
    public func registerButtonDestination(
        headers: Operations.RegisterButtonDestination.Input.Headers,
        body: Operations.RegisterButtonDestination.Input.Body
    ) async throws -> Operations.RegisterButtonDestination.Output {
        try await registerButtonDestination(Operations.RegisterButtonDestination.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/heartbeat/post(heartbeatButtonDestination)`.
    public func heartbeatButtonDestination(
        path: Operations.HeartbeatButtonDestination.Input.Path,
        headers: Operations.HeartbeatButtonDestination.Input.Headers,
        body: Operations.HeartbeatButtonDestination.Input.Body
    ) async throws -> Operations.HeartbeatButtonDestination.Output {
        try await heartbeatButtonDestination(Operations.HeartbeatButtonDestination.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/select`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/select/post(selectButtonDestination)`.
    public func selectButtonDestination(
        path: Operations.SelectButtonDestination.Input.Path,
        headers: Operations.SelectButtonDestination.Input.Headers,
        body: Operations.SelectButtonDestination.Input.Body
    ) async throws -> Operations.SelectButtonDestination.Output {
        try await selectButtonDestination(Operations.SelectButtonDestination.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/button-destinations/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/complete/post(completeButtonTake)`.
    public func completeButtonTake(
        path: Operations.CompleteButtonTake.Input.Path,
        headers: Operations.CompleteButtonTake.Input.Headers,
        body: Operations.CompleteButtonTake.Input.Body
    ) async throws -> Operations.CompleteButtonTake.Output {
        try await completeButtonTake(Operations.CompleteButtonTake.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /v1/button-destinations/{id}`.
    /// - Remark: Generated from `#/paths//v1/button-destinations/{id}/delete(unregisterButtonDestination)`.
    public func unregisterButtonDestination(
        path: Operations.UnregisterButtonDestination.Input.Path,
        headers: Operations.UnregisterButtonDestination.Input.Headers
    ) async throws -> Operations.UnregisterButtonDestination.Output {
        try await unregisterButtonDestination(Operations.UnregisterButtonDestination.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/audio-sources`.
    /// - Remark: Generated from `#/paths//v1/audio-sources/get(listAudioSources)`.
    public func listAudioSources(headers: Operations.ListAudioSources.Input.Headers = .init()) async throws -> Operations.ListAudioSources.Output {
        try await listAudioSources(Operations.ListAudioSources.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /v1/captures`.
    /// - Remark: Generated from `#/paths//v1/captures/post(startCapture)`.
    public func startCapture(
        headers: Operations.StartCapture.Input.Headers,
        body: Operations.StartCapture.Input.Body
    ) async throws -> Operations.StartCapture.Output {
        try await startCapture(Operations.StartCapture.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/capture/heartbeat`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/capture/heartbeat/post(heartbeatCapture)`.
    public func heartbeatCapture(
        path: Operations.HeartbeatCapture.Input.Path,
        headers: Operations.HeartbeatCapture.Input.Headers
    ) async throws -> Operations.HeartbeatCapture.Output {
        try await heartbeatCapture(Operations.HeartbeatCapture.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/capture/stop`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/capture/stop/post(stopCapture)`.
    public func stopCapture(
        path: Operations.StopCapture.Input.Path,
        headers: Operations.StopCapture.Input.Headers,
        body: Operations.StopCapture.Input.Body
    ) async throws -> Operations.StopCapture.Output {
        try await stopCapture(Operations.StopCapture.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/health`.
    /// - Remark: Generated from `#/paths//v1/health/get(getHealth)`.
    public func getHealth(headers: Operations.GetHealth.Input.Headers = .init()) async throws -> Operations.GetHealth.Output {
        try await getHealth(Operations.GetHealth.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/get(getPreferences)`.
    public func getPreferences(headers: Operations.GetPreferences.Input.Headers = .init()) async throws -> Operations.GetPreferences.Output {
        try await getPreferences(Operations.GetPreferences.Input(headers: headers))
    }
    /// - Remark: HTTP `PUT /v1/preferences`.
    /// - Remark: Generated from `#/paths//v1/preferences/put(updatePreferences)`.
    public func updatePreferences(
        headers: Operations.UpdatePreferences.Input.Headers = .init(),
        body: Operations.UpdatePreferences.Input.Body
    ) async throws -> Operations.UpdatePreferences.Output {
        try await updatePreferences(Operations.UpdatePreferences.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/get(listGenerations)`.
    public func listGenerations(
        query: Operations.ListGenerations.Input.Query = .init(),
        headers: Operations.ListGenerations.Input.Headers = .init()
    ) async throws -> Operations.ListGenerations.Output {
        try await listGenerations(Operations.ListGenerations.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations`.
    /// - Remark: Generated from `#/paths//v1/generations/post(createGeneration)`.
    public func createGeneration(
        headers: Operations.CreateGeneration.Input.Headers = .init(),
        body: Operations.CreateGeneration.Input.Body
    ) async throws -> Operations.CreateGeneration.Output {
        try await createGeneration(Operations.CreateGeneration.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/get(getGeneration)`.
    public func getGeneration(
        path: Operations.GetGeneration.Input.Path,
        headers: Operations.GetGeneration.Input.Headers = .init()
    ) async throws -> Operations.GetGeneration.Output {
        try await getGeneration(Operations.GetGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `DELETE /v1/generations/{id}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delete(deleteGeneration)`.
    public func deleteGeneration(
        path: Operations.DeleteGeneration.Input.Path,
        headers: Operations.DeleteGeneration.Input.Headers = .init()
    ) async throws -> Operations.DeleteGeneration.Output {
        try await deleteGeneration(Operations.DeleteGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/audio/{kind}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/audio/{kind}/post(appendAudio)`.
    public func appendAudio(
        path: Operations.AppendAudio.Input.Path,
        query: Operations.AppendAudio.Input.Query,
        headers: Operations.AppendAudio.Input.Headers = .init(),
        body: Operations.AppendAudio.Input.Body
    ) async throws -> Operations.AppendAudio.Output {
        try await appendAudio(Operations.AppendAudio.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/finish`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/finish/post(finishGeneration)`.
    public func finishGeneration(
        path: Operations.FinishGeneration.Input.Path,
        headers: Operations.FinishGeneration.Input.Headers = .init(),
        body: Operations.FinishGeneration.Input.Body
    ) async throws -> Operations.FinishGeneration.Output {
        try await finishGeneration(Operations.FinishGeneration.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/cancel`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/cancel/post(cancelGeneration)`.
    public func cancelGeneration(
        path: Operations.CancelGeneration.Input.Path,
        headers: Operations.CancelGeneration.Input.Headers = .init()
    ) async throws -> Operations.CancelGeneration.Output {
        try await cancelGeneration(Operations.CancelGeneration.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/generations/{id}/delivery`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/delivery/post(recordDelivery)`.
    public func recordDelivery(
        path: Operations.RecordDelivery.Input.Path,
        headers: Operations.RecordDelivery.Input.Headers = .init(),
        body: Operations.RecordDelivery.Input.Body
    ) async throws -> Operations.RecordDelivery.Output {
        try await recordDelivery(Operations.RecordDelivery.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// A bounded NDJSON stream of complete GenerationRecord values, with the latest record repeated as a two-second heartbeat. Ends after a terminal record.
    ///
    /// - Remark: HTTP `GET /v1/generations/{id}/events`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/events/get(generationEvents)`.
    public func generationEvents(
        path: Operations.GenerationEvents.Input.Path,
        headers: Operations.GenerationEvents.Input.Headers = .init()
    ) async throws -> Operations.GenerationEvents.Output {
        try await generationEvents(Operations.GenerationEvents.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/generations/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/generations/{id}/artifacts/{filename}/get(downloadArtifact)`.
    public func downloadArtifact(
        path: Operations.DownloadArtifact.Input.Path,
        headers: Operations.DownloadArtifact.Input.Headers = .init()
    ) async throws -> Operations.DownloadArtifact.Output {
        try await downloadArtifact(Operations.DownloadArtifact.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/known`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/known/post(knownWisprFlowIDs)`.
    public func knownWisprFlowIDs(
        headers: Operations.KnownWisprFlowIDs.Input.Headers = .init(),
        body: Operations.KnownWisprFlowIDs.Input.Body
    ) async throws -> Operations.KnownWisprFlowIDs.Output {
        try await knownWisprFlowIDs(Operations.KnownWisprFlowIDs.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/post(beginWisprFlowImport)`.
    public func beginWisprFlowImport(
        headers: Operations.BeginWisprFlowImport.Input.Headers = .init(),
        body: Operations.BeginWisprFlowImport.Input.Body
    ) async throws -> Operations.BeginWisprFlowImport.Output {
        try await beginWisprFlowImport(Operations.BeginWisprFlowImport.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/dictionary`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/dictionary/put(archiveWisprFlowDictionary)`.
    public func archiveWisprFlowDictionary(
        headers: Operations.ArchiveWisprFlowDictionary.Input.Headers = .init(),
        body: Operations.ArchiveWisprFlowDictionary.Input.Body
    ) async throws -> Operations.ArchiveWisprFlowDictionary.Output {
        try await archiveWisprFlowDictionary(Operations.ArchiveWisprFlowDictionary.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /v1/imports/wispr-flow/{id}/artifacts/{filename}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/artifacts/{filename}/put(uploadWisprFlowArtifact)`.
    public func uploadWisprFlowArtifact(
        path: Operations.UploadWisprFlowArtifact.Input.Path,
        headers: Operations.UploadWisprFlowArtifact.Input.Headers = .init(),
        body: Operations.UploadWisprFlowArtifact.Input.Body
    ) async throws -> Operations.UploadWisprFlowArtifact.Output {
        try await uploadWisprFlowArtifact(Operations.UploadWisprFlowArtifact.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/imports/wispr-flow/{id}/complete`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/complete/post(completeWisprFlowImport)`.
    public func completeWisprFlowImport(
        path: Operations.CompleteWisprFlowImport.Input.Path,
        headers: Operations.CompleteWisprFlowImport.Input.Headers = .init()
    ) async throws -> Operations.CompleteWisprFlowImport.Output {
        try await completeWisprFlowImport(Operations.CompleteWisprFlowImport.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `DELETE /v1/imports/wispr-flow/{id}`.
    /// - Remark: Generated from `#/paths//v1/imports/wispr-flow/{id}/delete(cancelWisprFlowImport)`.
    public func cancelWisprFlowImport(
        path: Operations.CancelWisprFlowImport.Input.Path,
        headers: Operations.CancelWisprFlowImport.Input.Headers = .init()
    ) async throws -> Operations.CancelWisprFlowImport.Output {
        try await cancelWisprFlowImport(Operations.CancelWisprFlowImport.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://localhost:8391",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://localhost:8391",
            variables: []
        )
    }
}
