// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
public import Foundation
extension Components {
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct APIError: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/APIError/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/APIError/content/application\/json`.
                case json(Components.Schemas.APIErrorResponse)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.APIErrorResponse {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.APIError.Body
            /// Creates a new `APIError`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.APIError.Body) {
                self.body = body
            }
        }
    }
}
